config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('post/', include('post.urls', namespace='post')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import *

app_name = 'main'

urlpatterns = [
    path('', home, name='home'),
]

post/urls.py
from django.urls import path
from .views import *

app_name = 'post'

urlpatterns = [
    path('<int:pk>/', blog_single, name='blog-single'),
]

main/models.py
from django.db import models

# Create your models here.


class GitInTouch(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Service(models.Model):
    icon = models.CharField(max_length=255)
    profession = models.CharField(max_length=255)
    content = models.TextField()

    def __str__(self):
        return self.profession

person/models.py
from django.db import models
from post.models import Category


# Create your models here.


class Partner(models.Model):
    image = models.ImageField(upload_to='icon')

    def __str__(self):
        return self.image.name


class About(models.Model):
    name = models.CharField(max_length=255)
    image = models.ImageField(upload_to='author')
    birthday = models.DateField()
    bio = models.TextField(null=True, blank=True)
    address = models.CharField(max_length=255)
    zip_code = models.IntegerField()
    email = models.EmailField()
    phone = models.CharField(max_length=255)
    projects = models.IntegerField()

    def __str__(self):
        return self.name


class Projects(models.Model):
    image = models.ImageField(upload_to='projects')
    category = models.ManyToManyField(Category, blank=True)
    link = models.URLField(null=True, blank=True)
    profession = models.CharField(max_length=255)

    def __str__(self):
        return self.profession


class Resume(models.Model):
    type = models.CharField(max_length=255)
    is_skill = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.type


class AdditionalInfo(models.Model):
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE)

    # experience
    profession = models.CharField(max_length=255, blank=True, null=True)
    start_finish = models.CharField(max_length=255, null=True, blank=True)
    academy = models.CharField(max_length=255, null=True, blank=True)
    icon = models.CharField(max_length=255, null=True, blank=True)
    content = models.TextField(null=True, blank=True)

    # is skill
    name = models.CharField(max_length=255, null=True, blank=True, verbose_name='Skill name')
    percent = models.IntegerField(null=True, blank=True)
    is_main = models.BooleanField(default=False)

    @property
    def last_week(self):
        lw = self.percent / 4
        return round(lw)

    @property
    def last_month(self):
        lm = self.percent / 12
        return round(lm)

post/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.

class Category(models.Model):
    category = models.CharField(max_length=255)

    def __str__(self):
        return self.category


class Tag(models.Model):
    tag = models.CharField(max_length=255)

    def __str__(self):
        return self.tag


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='posts')
    tags = models.ManyToManyField(Tag)
    content = models.TextField()
    author_name = models.CharField(max_length=255)
    avatar = models.ImageField(upload_to='author')
    author_commit = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    avatar = models.ImageField(upload_to='comments')
    website = models.URLField(null=True)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

main/forms.py
from django import forms
from .models import GitInTouch


class GitInTouchForm(forms.ModelForm):
    class Meta:
        model = GitInTouch
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(GitInTouchForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field_name.capitalize()

post/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = '__all__'
        exclude = ['post']

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field_name.capitalize()

main/views.py
from django.shortcuts import render
from .models import *
from post.models import *
from person.models import *
from .forms import GitInTouchForm

# Create your views here.


def home(request):
    posts = Post.objects.order_by('-id')
    form = GitInTouchForm(request.POST or None)
    if form.is_valid():
        form.save()
    projects = Projects.objects.order_by('-id')
    services = Service.objects.order_by('-id')
    resumes = Resume.objects.all()
    abouts = About.objects.order_by('-id')
    partners = Partner.objects.all()
    s = request.GET.get('s')
    if s:
        posts = posts.filter(title__icontains=s)
    ctx = {
        'posts': posts[:3],
        'form': form,
        'projects': projects[:6],
        'services': services[:6],
        'resumes': resumes,
        'abouts': abouts[:1],
        'partners': partners
    }
    return render(request, 'index.html', ctx)

person/views.py
from django.shortcuts import render

# Create your views here.

post/views.py
from django.shortcuts import render
from .models import *
from .forms import CommentForm

# Create your views here.


def blog_single(request, pk):
    post = Post.objects.get(id=pk)
    form = CommentForm(request.POST or None, request.FILES)
    if form.is_valid():
        commit = form.save(commit=False)
        commit.post = post
        commit.save()
    tags = Tag.objects.all()
    categories = Category.objects.all()
    ls = Post.objects.order_by('-id')
    ctx = {
        'form': form,
        'post': post,
        'tags': tags,
        'categories': categories,
        'last_3_posts': ls
    }
    return render(request, 'single.html', ctx)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Xolmatov Dilshod Olim o'g'li</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900" rel="stylesheet">
    <link rel="stylesheet"
          href="{% static 'css/A.open-iconic-bootstrap.min.css+animate.css+owl.carousel.min.css+owl.theme.default.min.css+magnific-popup.css+aos.css+ionicons.min.css+flaticon.css+icomoon.css+style.css,Mcc.03G1SaxbUZ.css' %}"/>
    <script nonce="406884c1-3e1a-4b67-ab69-d099fd88b46a">(function (w, d) {
        !function (a, e, t, r) {
            a.zarazData = a.zarazData || {}, a.zarazData.executed = [], a.zaraz = {deferred: []}, a.zaraz.q = [], a.zaraz._f = function (e) {
                return function () {
                    var t = Array.prototype.slice.call(arguments);
                    a.zaraz.q.push({m: e, a: t})
                }
            };
            for (const e of ["track", "set", "ecommerce", "debug"]) a.zaraz[e] = a.zaraz._f(e);
            a.addEventListener("DOMContentLoaded", (() => {
                var t = e.getElementsByTagName(r)[0], z = e.createElement(r), n = e.getElementsByTagName("title")[0];
                for (n && (a.zarazData.t = e.getElementsByTagName("title")[0].text), a.zarazData.x = Math.random(), a.zarazData.w = a.screen.width, a.zarazData.h = a.screen.height, a.zarazData.j = a.innerHeight, a.zarazData.e = a.innerWidth, a.zarazData.l = a.location.href, a.zarazData.r = e.referrer, a.zarazData.k = a.screen.colorDepth, a.zarazData.n = e.characterSet, a.zarazData.o = (new Date).getTimezoneOffset(), a.zarazData.q = []; a.zaraz.q.length;) {
                    const e = a.zaraz.q.shift();
                    a.zarazData.q.push(e)
                }
                z.defer = !0;
                for (const e of [localStorage, sessionStorage]) Object.keys(e).filter((a => a.startsWith("_zaraz_"))).forEach((t => {
                    try {
                        a.zarazData["z_" + t.slice(7)] = JSON.parse(e.getItem(t))
                    } catch {
                        a.zarazData["z_" + t.slice(7)] = e.getItem(t)
                    }
                }));
                z.referrerPolicy = "origin", z.src = "https://preview.colorlib.com/cdn-cgi/zaraz/s.js?z=" + btoa(encodeURIComponent(JSON.stringify(a.zarazData))), t.parentNode.insertBefore(z, t)
            }))
        }(w, d, 0, "script");
    })(window, document);</script>
</head>
<body data-spy="scroll" data-target=".site-navbar-target" data-offset="300">
<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar ftco-navbar-light site-navbar-target" id="ftco-navbar">
    <div class="container">
        <a class="navbar-brand" href="/#about-section"><span>D</span>ilshod</a>
        <button class="navbar-toggler js-fh5co-nav-toggle fh5co-nav-toggle" type="button" data-toggle="collapse"
                data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="oi oi-menu"></span> Menu
        </button>
        <div class="collapse navbar-collapse" id="ftco-nav">
            <ul class="navbar-nav nav ml-auto">
                <li class="nav-item"><a href="/#home-section" class="nav-link"><span>Home</span></a></li>
                <li class="nav-item"><a href="/#about-section" class="nav-link"><span>About</span></a></li>
                <li class="nav-item"><a href="/#resume-section" class="nav-link"><span>Resume</span></a></li>
                <li class="nav-item"><a href="/#services-section" class="nav-link"><span>Services</span></a></li>
                <li class="nav-item"><a href="/#projects-section" class="nav-link"><span>Projects</span></a></li>
                <li class="nav-item"><a href="/#blog-section" class="nav-link"><span>My Blog</span></a></li>
                <li class="nav-item"><a href="/#contact-section" class="nav-link"><span>Contact</span></a></li>
            </ul>
        </div>
    </div>
</nav>

{% block content %}

{% endblock %}

<footer class="ftco-footer ftco-section">
    <div class="container">
        <div class="row mb-5">
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">About</h2>
                    <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there
                        live the blind texts.</p>
                    <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                        <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                        <li class="ftco-animate"><a href="https://t.me/Muhammad_Rauf404"><span class="icon-telegram"></span></a></li>
                        <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                        <li class="ftco-animate"><a href="https://www.instagram.com/python_beckend_dev/"><span class="icon-instagram"></span></a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4 ml-md-4">
                    <h2 class="ftco-heading-2">Links</h2>
                    <ul class="list-unstyled">
                        <li><a href="#home-section"><span class="icon-long-arrow-right mr-2"></span>Home</a></li>
                        <li><a href="#about-section"><span class="icon-long-arrow-right mr-2"></span>About</a></li>
                        <li><a href="#services-section"><span class="icon-long-arrow-right mr-2"></span>Services</a></li>
                        <li><a href="#projects-section"><span class="icon-long-arrow-right mr-2"></span>Projects</a></li>
                        <li><a href="#contact-section"><span class="icon-long-arrow-right mr-2"></span>Contact</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Services</h2>
                    <ul class="list-unstyled">
                        <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Web Design</a></li>
                        <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Web Development</a></li>
                        <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Business Strategy</a></li>
                        <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Data Analysis</a></li>
                        <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Graphic Design</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Have a Questions?</h2>
                    <div class="block-23 mb-3">
                        <ul>
                            <li><span class="icon icon-map-marker"></span><span class="text">Krasnagorsk Oydin 49-29, Tashkent, Uzbekistan</span></li>
                            <li><a href="#"><span class="icon icon-phone"></span><span
                                    class="text">+998 93 090 19 16</span></a></li>
                            <li><a href="#"><span class="icon icon-envelope"></span><span class="text"><span>seferonxkiller@gmail.com</span></span></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 text-center">
                <p>
                    Copyright by <a
                        href="https://t.me/Muhammad_Rauf404" target="_blank">Dilshod</a>
                </p>
            </div>
        </div>
    </div>
</footer>

<div id="ftco-loader" class="show fullscreen">
    <svg class="circular" width="48px" height="48px">
        <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/>
        <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
                stroke="#F96D00"/>
    </svg>
</div>
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/jquery-migrate-3.0.1.min.js+popper.min.js+bootstrap.min.js.pagespeed.jc.bMyveoHKiv.js' %}"></script>
<script>eval(mod_pagespeed_gb7yraQys5);</script>
<script>eval(mod_pagespeed_RGKn6SW32g);</script>
<script>eval(mod_pagespeed_h9rX52Z4Ti);</script>
<script src="{% static 'js/jquery.easing.1.3.js+jquery.waypoints.min.js+jquery.stellar.min.js+owl.carousel.min.js.pagespeed.jc.P2hE5bOhqO.js' %}"></script>
<script>eval(mod_pagespeed_rBeIzFEDC0);</script>
<script>eval(mod_pagespeed_m_l$l00rWq);</script>
<script>eval(mod_pagespeed_tOGOF_KHft);</script>
<script>eval(mod_pagespeed_g921z9MGXC);</script>
<script src="{% static 'js/jquery.magnific-popup.min.js+aos.js+jquery.animateNumber.min.js+scrollax.min.js+main.js.pagespeed.jc.GTDEZB3xMJ.js' %}"></script>
<script>eval(mod_pagespeed_P9B3uJNt60);</script>
<script>eval(mod_pagespeed_ACE0ce7fTR);</script>
<script>eval(mod_pagespeed_awRnuKerVJ);</script>
<script>eval(mod_pagespeed_iVOyfib5U4);</script>
<script>eval(mod_pagespeed_udwuFYXF0f);</script>

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
<script>
    window.dataLayer = window.dataLayer || [];

    function gtag() {
        dataLayer.push(arguments);
    }

    gtag('js', new Date());

    gtag('config', 'UA-23581568-13');
</script>
<script defer src="https://static.cloudflareinsights.com/beacon.min.js/v652eace1692a40cfa3763df669d7439c1639079717194"
        integrity="sha512-Gi7xpJR8tSkrpF7aordPZQlW2DLtzUlZcumS8dMQjwDHEnw9I7ZLyiOj/6tZStRBGtGgN6ceN6cMH8z7etPGlw=="
        data-cf-beacon='{"rayId":"7174f0524bfb1239","token":"cd0b4b3a733644fc843ef0b185f98241","version":"2021.12.0","si":100}'
        crossorigin="anonymous"></script>
</body>
</html>

templates/blog.html
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
<script nonce="0c8bc48d-7464-4e73-b436-f271e23dee93">(function(w,d){!function(a,e,t,r){a.zarazData=a.zarazData||{},a.zarazData.executed=[],a.zaraz={deferred:[]},a.zaraz.q=[],a.zaraz._f=function(e){return function(){var t=Array.prototype.slice.call(arguments);a.zaraz.q.push({m:e,a:t})}};for(const e of["track","set","ecommerce","debug"])a.zaraz[e]=a.zaraz._f(e);a.addEventListener("DOMContentLoaded",(()=>{var t=e.getElementsByTagName(r)[0],z=e.createElement(r),n=e.getElementsByTagName("title")[0];for(n&&(a.zarazData.t=e.getElementsByTagName("title")[0].text),a.zarazData.x=Math.random(),a.zarazData.w=a.screen.width,a.zarazData.h=a.screen.height,a.zarazData.j=a.innerHeight,a.zarazData.e=a.innerWidth,a.zarazData.l=a.location.href,a.zarazData.r=e.referrer,a.zarazData.k=a.screen.colorDepth,a.zarazData.n=e.characterSet,a.zarazData.o=(new Date).getTimezoneOffset(),a.zarazData.q=[];a.zaraz.q.length;){const e=a.zaraz.q.shift();a.zarazData.q.push(e)}z.defer=!0;for(const e of[localStorage,sessionStorage])Object.keys(e).filter((a=>a.startsWith("_zaraz_"))).forEach((t=>{try{a.zarazData["z_"+t.slice(7)]=JSON.parse(e.getItem(t))}catch{a.zarazData["z_"+t.slice(7)]=e.getItem(t)}}));z.referrerPolicy="origin",z.src="/cdn-cgi/zaraz/s.js?z="+btoa(encodeURIComponent(JSON.stringify(a.zarazData))),t.parentNode.insertBefore(z,t)}))}(w,d,0,"script");})(window,document);</script></head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
<hr>
<address>Apache/2.4.41 (Ubuntu) Server at preview.colorlib.com Port 443</address>
<script defer src="https://static.cloudflareinsights.com/beacon.min.js/v652eace1692a40cfa3763df669d7439c1639079717194" integrity="sha512-Gi7xpJR8tSkrpF7aordPZQlW2DLtzUlZcumS8dMQjwDHEnw9I7ZLyiOj/6tZStRBGtGgN6ceN6cMH8z7etPGlw==" data-cf-beacon='{"rayId":"7174f1596b781239","token":"cd0b4b3a733644fc843ef0b185f98241","version":"2021.12.0","si":100}' crossorigin="anonymous"></script>
</body></html>

templates/single.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="hero-wrap js-fullheight">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text js-fullheight justify-content-center align-items-center">
            <div class="col-lg-10 ftco-animate d-flex align-items-center">
                <div class="text text-center">
                    <h1 class="mb-3 bread">Blog Single Post</h1>
                    <p class="breadcrumbs"><span class="mr-2"><a href="/#home-section">Home <i
                            class="ion-ios-arrow-forward"></i></a></span> <span class="mr-2"><a href="/#blog-section">Blog <i
                            class="ion-ios-arrow-forward"></i></a></span> <span>Blog Single <i
                            class="ion-ios-arrow-forward"></i></span></p>
                </div>
            </div>
        </div>
    </div>
</div>
<section class="ftco-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 ftco-animate">
                <h2 class="mb-3">{{ post.title }}</h2>
                <p><img src="{{ post.image.url }}" alt="" class="img-fluid"></p>
                <p>{{ post.content }}</p>
                <div class="tag-widget post-tag-container mb-5 mt-5">
                    <div class="tagcloud">
                        {% for tag in post.tags.all %}
                            <a class="tag-cloud-link">{{ tag }}</a>
                        {% endfor %}
                    </div>
                </div>
                <div class="about-author d-flex p-4 bg-light">
                    <div class="bio mr-5">
                        <img src="{{ post.avatar.url }}" alt="Image placeholder" class="img-fluid mb-4">
                    </div>
                    <div class="desc">
                        <h3>{{ post.author_name }}</h3>
                        <p>{{ post.author_commit }}</p>
                    </div>
                </div>
                <div class="pt-5 mt-5">
                    <h3 class="mb-5">{{ post.comment_set.count }} Comments</h3>
                    <ul class="comment-list">
                        {% for comment in post.comment_set.all %}
                            <li class="comment">
                            <div class="vcard bio">
                                {% if comment.avatar %}
                                    <img src="{{ comment.avatar.url }}" alt="Image placeholder">
                                {% else %}
                                    <img src="{% static 'images/user.jpg' %}" alt="Image placeholder">
                                {% endif %}
                            </div>
                            <div class="comment-body">
                                <h3>{{ comment.name }}</h3>
                                <div class="meta">{{ comment.created_at }}</div>
                                <p>{{ comment.message }}</p>
                            </div>
                        </li>
                        {% endfor %}
                    </ul>

                    <div class="comment-form-wrap pt-5">
                        <h3 class="mb-5">Leave a comment</h3>
                        <form method="post" class="p-5 bg-light" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="name">Name *</label>
                                {{ form.name }}
                            </div>
                            <div class="form-group">
                                <label for="email">Email *</label>
                                {{ form.email }}
                            </div>
                            <div class="form-group">
                                <label for="image">Image</label>
                                {{ form.avatar }}
                            </div>
                            <div class="form-group">
                                <label for="website">Website</label>
                                {{ form.website }}
                            </div>
                            <div class="form-group">
                                <label for="message">Message</label>
                                {{ form.message }}
                            </div>
                            <div class="form-group">
                                <input type="submit" value="Post Comment" class="btn py-3 px-4 btn-primary">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 sidebar ftco-animate">
                <div class="sidebar-box">
                    <form method="get" action="/#blog-section" class="search-form">
                        <div class="form-group">
                            <span class="icon icon-search"></span>
                            <input type="search" name="s" class="form-control" placeholder="Search...">
                        </div>
                    </form>
                </div>
                <div class="sidebar-box ftco-animate">
                    <h3 class="heading-sidebar">Categories</h3>
                    <ul class="categories">
                        {% for category in categories %}
                            <li><a>{{ category }} <span>({{ category.post_set.count }})</span></a></li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="sidebar-box ftco-animate">
                    <h3 class="heading-sidebar">Recent Blog</h3>
                    {% for last_3_post in last_3_posts %}
                        <div class="block-21 mb-4 d-flex">
                        <a class="blog-img mr-4" style="background-image: url({{ last_3_post.image.url }});"></a>
                        <div class="text">
                            <h3 class="heading"><a href="{% url 'post:blog-single' last_3_post.id %}">{{ last_3_post.title|slice:'100'}}</a></h3>
                            <div class="meta">
                                <div><a><span class="icon-calendar"></span> {{ last_3_post.created_at }}</a></div>
                                <div><a><span class="icon-person"></span> {{ last_3_post.author }}</a></div>
                                <div><a><span class="icon-chat"></span> {{ last_3_post.comment_set.count }}</a></div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                <div class="sidebar-box ftco-animate">
                    <h3 class="heading-sidebar">Tag Cloud</h3>
                    <div class="tagcloud">
                        {% for tag in tags %}
                            <a class="tag-cloud-link">{{ tag }}</a>
                        {% endfor %}
                    </div>
                </div>
                <div class="sidebar-box ftco-animate">
                    <h3 class="heading-sidebar">Paragraph</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus itaque, autem necessitatibus
                        voluptate quod mollitia delectus aut, sunt placeat nam vero culpa sapiente consectetur
                        similique, inventore eos fugit cupiditate numquam!</p>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}